name: clever cloud

on:
  push:
    branches:
      - main
jobs:
  deploy:
    image:
      name: clevercloud/clever-tools
      entrypoint: [ "/bin/sh", "-c" ]
    stage: deploy
    script:
      - clever deploy --force