name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  FRONT_END_APP_ID: ${{ secrets.FE_APP_ID }}
  BACK_END_APP_ID: ${{ secrets.BE_APP_ID }}

jobs:

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy backend image to Clever Cloud
      uses: 47ng/actions-clever-cloud@master
      with:
        app-id: ${{ env.BACK_END_APP_ID }}
        image: bourahma/shoploc-be:latest

    - name: Deploy frontend image to Clever Cloud
      uses: 47ng/actions-clever-cloud@master
      with:
        app-id: ${{ env.FRONT_END_APP_ID }}
        image: bourahma/shoploc-fe:latest