name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  FRONT_END_APP_ID: ${{ secrets.FE_APP_ID }}
  BACK_END_APP_ID: ${{ secrets.BE_APP_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set production profile
        run: |
          sed -i 's/spring.profiles.active=dev/spring.profiles.active=prod/g' ./shoploc-be/src/main/resources/application.properties

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and deploy shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-be
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-be:latest

      # Build and deploy shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-fe
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-fe:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Deploy backend image to Clever Cloud
      uses: 47ng/actions-clever-cloud@master
      env:
        CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
        CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
      with:
        app-id: ${{ env.BE_APP_ID }}
        image: bourahma/shoploc-be:latest

    - name: Deploy frontend image to Clever Cloud
      uses: 47ng/actions-clever-cloud@master
      with:
        app-id: ${{ env.FE_APP_ID }}
        image: bourahma/shoploc-fe:latest