name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  IP_BE_ADDRESS: ${{ secrets.AWS_PRIVATE_KEY }}
  IP_FE_ADDRESS: ${{ secrets.IP_FE_ADDRESS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and deploy shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-be
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-be:latest

      # Build and deploy shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-fe
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-fe:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      # Deploy shoploc-be on EC2 instance.
      - name: Pull shoploc-be docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.38.106.88 'sudo docker pull bourahma/shoploc-be:latest'
      - name: Stop running shoploc-be-container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.38.106.88 'sudo docker stop shoploc-be-container || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.38.106.88 'sudo docker rm shoploc-be-container || true'
      - name: Run new shoploc-be-container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.38.106.88 'sudo docker run -d --name shoploc-be-container -p 80:8080 bourahma/shoploc-be:latest'

      # Deploy shoploc-fe on EC2 instance.
      - name: Pull shoploc-fe docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@35.181.56.65 'sudo docker pull bourahma/shoploc-fe:latest'
      - name: Stop running shoploc-fe-container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@35.181.56.65 'sudo docker stop shoploc-fe-container || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@35.181.56.65 'sudo docker rm shoploc-fe-container || true'
      - name: Run new shoploc-fe-container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@35.181.56.65 'sudo docker run -d --name shoploc-fe-container -p 80:3000 bourahma/shoploc-be:latest'