name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IP_BE_ADDRESS: ${{ secrets.IP_BE_ADDRESS }}
  IP_FE_ADDRESS: ${{ secrets.IP_FE_ADDRESS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set production profile
        run: |
          sed -i 's/spring.profiles.active=dev/spring.profiles.active=prod/g' ./shoploc-be/src/main/resources/application.properties

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-be
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-be:latest

      # Build and push shoploc-be image on docker hub.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shoploc-fe
          push: true
          dockerfile: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shoploc-fe:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Install VPN to access OpenStack with univ lille credentials
      - name: Install OpenVPN Client
        run: sudo apt-get update && sudo apt-get install openvpn

      - name: Download VPN Configuration
        run: |
            wget https://infotuto.univ-lille.fr/fileadmin/user_upload/infotuto/images/DSI/Fichiers_telechargeables/Clients_VPN/ULILLE_VPN_ETUDIANT_Linux_v4.zip
            unzip ULILLE_VPN_ETUDIANT_Linux_v4.zip

      - name: OpenVPN-Connect
        uses: kota65535/github-openvpn-connect-action@v2.1.0
        with:
          config_file: ULILLE_VPN_ETU_TCP_v4_Linux.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      # Login to docker hub.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set permissions for private key
        run:
          chmod 600 shoploc.pem

      # Deploy shoploc-be on OpenStack instance.
      - name: Pull shoploc-be docker image
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_BE_ADDRESS 'sudo docker pull bourahma/shoploc-be:latest'
      - name: Stop running shoploc-be-container
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_BE_ADDRESS 'sudo docker stop shoploc-be-container || true'
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_BE_ADDRESS 'sudo docker rm shoploc-be-container || true'
      - name: Run new shoploc-be-container
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_BE_ADDRESS 'sudo docker run -d --name shoploc-be-container -p 80:8080 bourahma/shoploc-be:latest'

      # Deploy shoploc-fe on OpenStack instance.
      - name: Pull shoploc-fe docker image
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_FE_ADDRESS 'sudo docker pull bourahma/shoploc-fe:latest'
      - name: Stop running shoploc-fe-container
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_FE_ADDRESS 'sudo docker stop shoploc-fe-container || true'
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_FE_ADDRESS 'sudo docker rm shoploc-fe-container || true'
      - name: Run new shoploc-fe-container
        run: |
          ssh -i shoploc.pem -o StrictHostKeyChecking=no ubuntu@$IP_FE_ADDRESS 'sudo docker run -d --name shoploc-fe-container -p 80:3000 bourahma/shoploc-fe:latest'