name: CI

on:
  push:
    branches:
      - '*'
jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        # CI  Tests
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '17'

        - name: Clean project
          run: |
            cd shoploc-be
            mvn clean

        - name: Run Tests
          run: |
            cd shoploc-be
            mvn test